faasapiurl: http://10.231.143.223:18991/hit/xrobot
cronstr: 0/20 * * * * ?

namenodeexporterip: localhost
namenodeexporterport: 9070
namenodejmx: http://10.231.144.251:50070/jmx

resourcemanagerjmx: http://10.231.144.251:8088
resourcemanagerexporterip: localhost
resourcemanagerexporterport: 9088

journalnodeexporterip: localhost
journalnodeexporterport: 9071
journalnodeexporterjmx: http://hdp03:8480/jmx

datanodejmx: http://localhost:50075/jmx
datanodeexporterip: localhost
datanodeexporterport: 9077


exportproject: MarketCenter_SaleTeam
exportappid: streamsets_monitor
exportskill: adbStreamsets-sinkMsgToEs


alertphone: 15828442734,15983253920
alertport: 8081
alertproject: MarketCenter_CRMTeam
alertappid: AlterMsgForCrm
alertskill: AlterMsgReceiveAndSend-AlterMsg






#startsendtime: 2017-01-02 08:08:08
#sendmaxcountperday: 100
#devices:
#  - devid: 123456789
#    nodes:
#      - pkid: 0
#        bkid: 0
#        index: 0
#        minvalue: 0
#        maxvalue: 60
#        datatype: normal
#      - pkid: 0
#        bkid: 0
#        index: 0
#        datatype: boolean
#  - devid: 10001
#    nodes:
#      - pkid: 0
#        bkid: 1
#        index: 0
#        datatype: boolean
#warnfrequency: 10
#sendfrequency: 10