ip: localhost
port: 9070
faasapiurl: http://10.231.143.223:18991/hit/xrobot
cronstr: 0/20 * * * * ?
startsendtime: 2017-01-02 08:08:08
sendmaxcountperday: 100
devices:
  - devid: 123456789
    nodes:
      - pkid: 0
        bkid: 0
        index: 0
        minvalue: 0
        maxvalue: 60
        datatype: normal
      - pkid: 0
        bkid: 0
        index: 0
        datatype: boolean
  - devid: 10001
    nodes:
      - pkid: 0
        bkid: 1
        index: 0
        datatype: boolean
warnfrequency: 10
sendfrequency: 10